In [1]:
import numpy as np

## Data types and attributes 


In [2]:
## main data type is nd array

In [3]:
a1 = np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a3 = np.array([[[1,2,3],
               [4,5,6]],
              
              [[7,8,9],
              [11,12,13]]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [12]:
 a1.shape

(3,)

In [13]:
a2.shape

(2, 3)

In [14]:
a3.shape

(2, 2, 3)

In [15]:
a1.ndim
a2.ndim
a3.ndim

3

In [16]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [17]:
a1.size, a2.size, a3.size

(3, 6, 12)

## Create dataframe out of numpy

In [18]:
import pandas as pd

In [19]:
df = pd.DataFrame(a2)

In [20]:
df

0  1  2
0  1  2  3
1  4  5  6

In [21]:
tf = pd.DataFrame(a3)

ValueError: Must pass 2-d input. shape=(2, 2, 3)

## Creating arrays

In [22]:
ones = np.ones((2,3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
ones.dtype

dtype('float64')

In [27]:
zeroes = np.zeros((2,3))

In [28]:
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
range_array = np.arange(0, 10, 2)

In [30]:
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(0, 10, size = (2,3))

In [33]:
random_array

array([[1, 5, 7],
       [5, 3, 0]])

In [37]:
## Pseudo random numbers ~ random numbers that can be reproduced
np.random.seed(0)

In [39]:
random_array

array([[1, 5, 7],
       [5, 3, 0]])

## Viewing arrays and matrices 

In [40]:
arr = np.array([1,1,2,4,1,3,3,6,2,9,3])

In [41]:
np.unique(arr)

array([1, 2, 3, 4, 6, 9])

In [42]:
a1

array([1, 2, 3])

In [43]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [45]:
a1[0]

1

In [46]:
a2[0]

array([1, 2, 3])

In [47]:
a2[0][0]

1

In [48]:
a3[1]

array([[ 7,  8,  9],
       [11, 12, 13]])

In [49]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a3[0][0]

array([1, 2, 3])

In [51]:
a3[0][0][0]

1

## Manipulating and comparing array

## Arithmetic

In [52]:
a1

array([1, 2, 3])

In [53]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [55]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [56]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [57]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [59]:
a1

array([1, 2, 3])

## Aggregation

In [70]:
a2_reshape = a2.reshape(2,3,1)

In [67]:
a2reshape.shape

(2, 3, 1)

In [71]:
a3reshape = a3.reshape(2,3,3)

ValueError: cannot reshape array of size 12 into shape (2,3,3)

## images to numbers

<img src="img/panda.png" />

In [75]:
from matplotlib.image import imread

In [76]:
panda = imread("img/panda.png")

In [77]:
print(type(panda))

<class 'numpy.ndarray'>


In [78]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [79]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

<img src="img/car-photo.png" />

In [80]:
car = imread("img/car-photo.png")

In [81]:
print(type(car))

<class 'numpy.ndarray'>


In [82]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [83]:
car[:-5]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

<img src="img/dog-photo.png" />

In [85]:
dog = imread("img/dog-photo.png")

In [86]:
dog


array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

<img src="img/flower.JPG" />

In [87]:
flower = imread("img/flower.JPG")

In [88]:
flower

array([[[62, 68, 66],
        [64, 70, 68],
        [66, 72, 70],
        ...,
        [28, 51,  9],
        [27, 52, 12],
        [21, 46,  7]],

       [[60, 69, 68],
        [63, 72, 71],
        [65, 74, 73],
        ...,
        [31, 52, 13],
        [30, 52, 14],
        [24, 46, 10]],

       [[60, 68, 70],
        [62, 71, 70],
        [65, 75, 74],
        ...,
        [34, 51, 15],
        [34, 51, 19],
        [27, 43, 16]],

       ...,

       [[ 8, 25, 32],
        [36, 53, 60],
        [43, 58, 65],
        ...,
        [ 9, 17, 19],
        [ 9, 19, 20],
        [ 9, 19, 20]],

       [[21, 36, 55],
        [43, 56, 75],
        [32, 43, 63],
        ...,
        [11, 16, 19],
        [ 8, 16, 18],
        [ 7, 15, 17]],

       [[31, 42, 74],
        [40, 51, 83],
        [20, 29, 62],
        ...,
        [11, 16, 19],
        [ 7, 12, 15],
        [ 2, 10, 12]]], dtype=uint8)